[project]
name = "ai-job-hunter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai>=0.102.0",
    "crewai-tools>=0.36.0",
    "dotenv>=0.9.9",
    "langchain-groq>=0.2.5",
    "langchain-huggingface>=0.1.2",
]
